@startuml

class de.officeryoda.fhysics.visual.QuadTree {

}


abstract class de.officeryoda.fhysics.engine.objects.FhysicsObject {
    {abstract} + type: FhysicsObjectType
    + color: Color
    angle: Float
}

' QTNode is a inner class of QuadTree
QuadTree *--  QTNode

@enduml